# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/drug_search_ai',
                'doc_host': 'https://abdelkareemkobo.github.io',
                'git_url': 'https://github.com/abdelkareemkobo/drug_search_ai',
                'lib_path': 'drug_search_ai'},
  'syms': {'drug_search_ai.core': {'drug_search_ai.core.foo': ('core.html#foo', 'drug_search_ai/core.py')}}}
